name: Build Image for ACR
on:
  push:
    branches: [master, gh-actions]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ACR build
        id: acr
        uses: azure/acr-build@v1
        with:
          service_principal: 443f1e0a-9923-4797-a7d4-501068357e88
          service_principal_password: ${{ secrets.service_principal_password }}
          tenant: b4a3e2d3-2d99-4b3e-a15e-5a85d655c544
          registry: /subscriptions/8d00305a-0cc3-4bc8-a8fc-320806a17895/resourceGroups/bostonbynight-gdr/providers/Microsoft.ContainerRegistry/registries/bostonbynightgdr
          repository: bostonbynight-gdr
          image: bostonbynight-gdr
          git_access_token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: DockerfileGithubAction
          branch: master
          args: |
            db_url=${{ secrets.POSTGRES_CONN_STRING }}
            secret_key=${{ secrets.SECRET_KEY_STRING }}
            mail_smtps_server=smtps.aruba.it
            mail_port=465
            mail_user=postmaster@vtmbaires.eu
            mail_pass=${{ secrets.MAIL_PWD }}